name: Actions Read Test

on:
  workflow_dispatch:

permissions:
  actions: read  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitHub API to list workflow runs
        run: |
          echo "Fetching workflow runs for ${{ github.repository }}..."
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/runs
