name: Minimal Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show GITHUB_TOKEN permissions
        run: |
          echo "Permissions for this token:"
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/permissions/workflow \
          | jq .

      - name: Try checkout (proves contents:read works by default)
        uses: actions/checkout@v4
